//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace кэ4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Zayavka = new HashSet<Zayavka>();
        }
    
        public int Id { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<Zayavka> Zayavka { get; set; }
    }
}
