//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace кэ4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        public int Id { get; set; }
        public Nullable<int> ZayavkaClientId { get; set; }
        public Nullable<int> ZayavkaArtistId { get; set; }
        public Nullable<int> ZayavkaObrydId { get; set; }
        public Nullable<int> ZayavkaStatusId { get; set; }
        public Nullable<int> ZayavkaTypeId { get; set; }
        public string ZayavkaDescription { get; set; }
        public string ZayavkaComment { get; set; }
        public Nullable<System.DateTime> ZayavkaDate { get; set; }
        public Nullable<int> ZayavkaNumber { get; set; }
    
        public virtual Artists Artists { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Oboryd Oboryd { get; set; }
        public virtual Status Status { get; set; }
        public virtual Type Type { get; set; }
    }
}
